import React from 'react';
import LandingTemplate from '../../components/layouts/LandingTemplate';

// And now we can use these
const PrivacyPolicy = () => {
  return (
    <LandingTemplate>
      <div className="my-container">
        <h1> Privacy Policy </h1>
        <p className="muted-text">Last Updated: 26th March, 2021. </p>
        <br />
        <p>Protecting your privacy is important to us. We therefore hope that the following statement will help you understand what Rhenda does with the personal information you may occasionally provide us.</p>
        <p>This privacy policy describes our policies and procedures on the collection, use and disclosure of your information when you use the service and tells you about your privacy rights and how the law protects you.</p>
        <p>We use your personal data to provide and improve the service. By using the service, you agree to the collection and use of information in accordance with this Privacy Policy.</p>
        <br />
        <h3>TABLE OF CONTENT:</h3>
        <br />
        <h5>
          <ul>
            <li>DEFINITIONS</li>
            <li>TYPES OF  DATA WE COLLECT</li>
            <li>USE OF YOUR PERSONAL DATA</li>
            <li>RETENTION OF YOUR PERSONAL DATA AND USAGE DATA</li>
            <li>TRANSFER OF YOUR PERSONAL DATA</li>
            <li>DISCLOSURE OF YOUR PERSONAL DATA</li>
            <li>SECURITY OF YOUR PERSONAL DATA</li>
            <li>DETAILED INFORMATION ON THE PROCESSING OF YOUR PERSONAL DATA</li>
            <li>TRACKING TECHNOLOGIES AND COOKIES</li>
            <li>USAGE, PERFORMANCE AND MISCELLANEOUS</li>
            <li>CHILDREN'S PRIVACY</li>
            <li>OUR ADVERTISING PARTNERS AND LINKS TO OTHER WEBSITES</li>
            <li>THIRD-PARTY PRIVACY POLICIES</li>
            <li>ABOUT THIS PRIVACY POLICY</li>
            <li>YOUR CONSENT</li>
            <li>CHANGES TO THIS PRIVACY POLICY</li>
            <li>CONTACT US</li>
          </ul>
        </h5>
        <br />
        <h2>•	DEFINITIONS</h2>
        <p>For the purposes of this Privacy Policy:</p>
        <p>Account means a unique account created for you to access the Service or parts of the Service.</p>
        <p>Company (referred to as either the Company, We, Us or Our in this Agreement) refers to Rhenda.</p>
        <p>Cookies are small files that are placed on your computer, mobile device or any other device by a website, containing the details of your browsing history on that website among its many uses.</p>
        <p>Country refers to Nigeria.</p>
        <p>Device means any device that can access the service such as a computer, a cellphone or a digital tablet.</p>
        <p>Personal Data is any information that relates to an identified or identifiable individual.</p>
        <p>Service refers to the website.</p>
        <p>Service Provider means any natural or legal person who processes the data on behalf of the company. It refers to third-party companies or individuals employed by the company to facilitate the service, to provide the service on behalf of the company, to perform services related to the service or to assist the company in analyzing how the service is used.</p>
        <p>Third-party Social Media Service refers to any website or any social network website through which a user can log in or create an account to use the Service.</p>
        <p>Usage Data refers to data collected automatically, either generated by the use of the service or from the service infrastructure itself (for example, the duration of a page visit).</p>
        <p>Website refers to Rhenda, accessible from "www.rhenda.com"</p>
        <p>You means the individual accessing or using the service, or the company, or other legal entity on behalf of which such individual is accessing or using the service, as applicable.</p>
        <br />
        <h2>•	TYPES OF DATA WE COLLECT</h2>
        <h5>1.	Personal Data</h5>
        <p>While using our service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include, but is not limited to:</p>
        <ul>
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
        </ul>

        <h5>2.	Usage Data</h5>
        <p>Usage Data is collected automatically when using the service. Usage Data may include information such as your service's internet protocol address (e.g. IP address), browser type, browser version, the pages of our service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data. When you access the service by or through a mobile device, we may collect certain information automatically, including, but not limited to:</p>
        <ul>
          <li>The type of mobile device you use</li>
          <li>Your mobile device unique ID</li>
          <li>The IP address of your mobile device</li>
          <li>Your mobile operating system</li>
          <li>The type of mobile internet browser you use</li>
          <li>Unique device identifiers and other diagnostic data</li>
        </ul>
        <p>We may also collect information that your browser sends whenever you visit our service or when you access the service by or through a mobile device. We may also collect information about your activity in our services. The activity information that we collect may include:</p>
        <ul>
          <li>Terms that you search for</li>
          <li>Videos that you watch</li>
          <li>Views and interactions with content and ads</li>
          <li>People with whom you communicate or share content</li>
          <li>Activity on third-party sites and apps that use our services</li>
        </ul>
        <p>If you use our services to make calls or send and receive messages, we may collect call and message log information like your phone number, calling-party number, receiving-party number, forwarding numbers, sender and recipient email address, time and date of calls and messages, duration of calls, routing information and types and volumes of calls and messages.</p>
        <p>We collect information about your location when you use our services.</p>
        <p>Your location can be determined with varying degrees of accuracy by:</p>
        <ul>
          <li>GPS</li>
          <li>IP address</li>
          <li>Sensor data from your device</li>
        </ul>
        <p>Information about things near your device, such as Wi-Fi access points, cell towers and Bluetooth-enabled devices.</p>
        <p>The types of location data that we collect depend in part on your device and account settings. For example, you can turn your Android device’s location on or off using the device’s settings app. You can also turn on Location History if you want to create a private map of where you go with your signed-in devices.</p>
        <br />
        <h2>•	USE OF YOUR PERSONAL DATA</h2>
        <p>The company may use Personal Data for the following purposes:</p>
        <ul>
          <li>To provide and maintain our service, including to monitor the usage of our service.</li>
          <li>To manage your account: to manage your registration as a user of the service. The Personal Data you provide can give ypu access to different functionalities of the service that are available to you as a registered user.</li>
          <li>For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services you have purchased or of any other contract with us through the service.</li>
          <li>To contact you: to contact you by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
          <li>To provide you with news, special offers and general information about other services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information.</li>
          <li>To attend to and manage your requests to us.</li>
          <li>For business transfers: we may use your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by us about our service users is among the assets transferred.</li>
          <li>For other purposes: we may use your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our service, products, services, marketing and your experience.</li>
        </ul>
        <p>We may share your personal information in the following situations:</p>
        <p>With Service Providers: we may share Your personal information with Service Providers to monitor and analyze the use of our service,  to contact you.</p>
        <p>For Business Transfers: we may share or transfer your personal information in connection with, or during negotiations of, any merger, sale of company assets, financing, or acquisition of all or a portion of Our business to another company.</p>
        <p>With Affiliates: we may share Your information with our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include our parent company and any other subsidiaries, joint venture partners or other companies that we control or that are under common control with us.
          With Business Partners: we may share your information with our business partners to offer you certain products, services or promotions.</p>
        <p>With Other Users: when you share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside. If you interact with other users or register through a Third-Party Social Media Service, your contacts on the Third-Party Social Media Service may see your name, profile, pictures and description of your activity. Similarly, other users will be able to view descriptions of your activity, communicate with you and view your profile.</p>
        <p>With Your Consent: we may disclose your personal information for any other purpose with your consent.</p>
        <br />
        <h2>•	RETENTION OF YOUR PERSONAL DATA AND USAGE DATA</h2>
        <p>The Company will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policy. The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our service, or we are legally obligated to retain this data for longer time periods.</p>
        <br />
        <h2>•	TRANSFER OF YOUR PERSONAL DATA</h2>
        <p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.</p>
        <p>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.
          The Company will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.</p>
        <br />
        <h2>•	DISCLOSURE OF YOUR PERSONAL DATA</h2>
        <h5>Business Transactions</h5>
        <p>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
        <h5>Law Enforcement</h5>
        <p>Under certain circumstances, the company may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency.</p>
        <h5>Other Legal Requirements</h5>
        <p>The Company may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
        <ul>
          <li>Comply with a legal obligation,</li>
          <li>Protect and defend the rights or property of the company,</li>
          <li>Prevent or investigate possible wrongdoing in connection with the service,</li>
          <li>Protect the personal safety of Users of the service or the public,</li>
          <li>Protect against legal liability.</li>
        </ul>
        <br />
        <h2>•	SECURITY OF YOUR PERSONAL DATA</h2>
        <p>The security of your Personal Data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>
        <br />
        <h2>•	DETAILED INFORMATION ON THE PROCESSING OF YOUR PERSONAL DATA</h2>
        <p>The Service Providers we use may have access to Your Personal Data. These third-party vendors collect, store, use, process and transfer information about your activity on our Service in accordance with their Privacy Policies.</p>
        <br />
        <h2>•	TRACKING TECHNOLOGIES AND COOKIES</h2>
        <p>We use Cookies and similar tracking technologies to track the activity on our service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze our service. The technologies we use may include:</p>
        <ul>
          <li><h5>Cookies or Browser Cookies</h5></li>
          <p>A cookie is a small file placed on your device. You can instruct your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if you do not accept Cookies, you may not be able to use some parts of our service. Unless you have adjusted your browser setting so that it will refuse Cookies, our service may use cookies.</p>
          <p>Cookies can be Persistent or Session Cookies.</p>
          <p>Persistent Cookies remain on your personal computer or mobile device when you go offline, while Session Cookies are deleted as soon as you close your web browser.</p>
          <p>Session Cookies are essential to provide you with services available through the website and to enable you to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that you have asked for cannot be provided, and we only use these Cookies to provide You with those services.</p>
          <p>Persistent Cookies help identify if users have accepted the use of cookies on the website. These Cookies allow us to remember choices you make when you use the website, such as remembering your login details or language preference. The purpose of these Cookies is to provide you with a more personal experience and to avoid you having to re-enter your preferences every time you use the website.</p>
          <p>For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy.</p>
          <li><h5>Flash Cookies</h5></li>
          <p>Certain features of our service may use local stored objects (or Flash Cookies) to collect and store information about your preferences or your activity on our service. Flash Cookies are not managed by the same browser settings as those used for Browser Cookies.</p>
          <li><h5>Web Beacons</h5></li>
          <p>Certain sections of our service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</p>
          <li><h5>Google DoubleClick DART Cookie</h5></li>
          <p>Google is one of a third-party vendor on our site. It also uses cookies, known as DART cookies, to serve ads to our site visitors based upon their visit to www.rhenda.com and other sites on the internet. However, visitors may choose to decline the use of DART cookies by visiting the Google ad and content network Privacy Policy.</p>
        </ul>
        <br />
        <h2>•	USAGE, PERFORMANCE AND MISCELLANEOUS</h2>
        <p>We may use Third-Party Service Providers to provide better improvement of our Service.</p>
        <h5>Google Places</h5>
        <p>Google Places is a service that returns information about places using HTTP requests. It is operated by Google. Google Places service may collect information from you and from your Device for security purposes.</p>
        <p>The information gathered by Google Places is held in accordance with the Privacy Policy of Google.</p>
        <h5>reCAPTCHA</h5>
        <p>reCAPTCHA is a CAPTCHA system that enables us to distinguish between human and automated access to our website. reCAPTCHA uses an advanced risk analysis engine and adaptive challenges to keep malicious software from engaging in abusive activities on our website. It allows you to login, view pages, or create accounts.</p>
        <h5>Google Analytics</h5>
        <p>Google Analytics is a web analytics service offered by Google that tracks and reports website traffic, currently as a platform inside the Google Marketing Platform brand.</p>
        <p>The information gathered by Google Analytics is held in accordance with the Privacy Policy of Google.</p>
        <br />
        <h2>•	CHILDREN'S PRIVACY</h2>
        <p>Our Service does not address anyone under the age of 18. We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your child or ward has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from anyone under the age of 18 without verification of parental consent, we take steps to remove that information from our servers.</p>
        <p>If we need to rely on consent as a legal basis for processing your information and your country requires consent from a parent, we may require your parent's consent before we collect and use that information.</p>
        <br />
        <h2>•	OUR ADVERTISING PARTNERS AND LINKS TO OTHER WEBSITES</h2>
        <p>Our service may contain links to other websites that are not operated by us and some of the advertisers on our website may use cookies and web beacons. If you click on a third party link, you will be directed to that third party's site. Each of our advertising partners has their own Privacy Policy on user data. We strongly advise you to review the Privacy Policy of every site you visit.</p>
        <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
          <br />
          <h2>•	THIRD-PARTY PRIVACY POLICIES</h2>
          <p>Rhenda's Privacy Policy does not apply to other advertisers or websites. Thus, we are advising you to consult the respective Privacy Policies of these third-party ad servers for more detailed information. It may include their practices and instructions about how to opt-out of certain options.
            You can choose to disable cookies through your individual browser options. To know more detailed information about cookie management with specific web browsers, it can be found at the browsers' respective websites.</p>
          <br />
          <h2>•	ABOUT THIS PRIVACY POLICY</h2>
          <p>This Privacy Policy applies only to our online activities and is valid for visitors to our website with regards to the information that they shared and/or collect in Rhenda. This policy is not applicable to any information collected offline or via channels other than this website.</p>
          <br />
          <h2>•	YOUR CONSENT</h2>
          <p>By using our website, you hereby consent to our Privacy Policy and agree to its Terms and Conditions.</p>
          <br />
          <h2>•	CHANGES TO THIS PRIVACY POLICY</h2>
          <p></p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
        <p>We will let you know via email and/or a prominent notice on our service, prior to the change becoming effective and update the date (Last Updated) at the top of this Privacy Policy.</p>
        <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
        <br />
        <h2>•	CONTACT US</h2>
        <p>If you have additional questions or require more information about our Privacy Policy, do not hesitate to contact us:</p>
        <p>By email: rhenda@gmail.com</p>
        <p>By visiting this page on our website: http:/www.rhenda.com/contact-us</p>
        <p>By phone number: +234 813 968 7140</p>

      </div>
    </LandingTemplate>
  );
};

export default PrivacyPolicy;
